version: "3"

services:
  redis:
    image: redis:6-alpine
    container_name: redis
    env_file:
      - .env
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - internal
    ports:
      - "6379:6379"

  postgres:
    image: postgres:13-alpine
    container_name: postgres
    networks:
      - internal
    volumes:
      - persistent:/var/lib/postgres/data
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgres/data
    ports:
      - "5432:5432"

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    networks:
      - internal
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  persistent:

networks:
  internal:
    driver: bridge
