name: libaaryapay
description: libaaryapay library
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  path: ^1.8.0
  cryptography: ^2.5.0
  uuid: ^3.0.6
  http: ^0.13.6
  flutter_secure_storage: ^8.0.0
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
