API_STR : "/api/v1"
SECRET_KEY : 28472B4B6250655368566D5971337436763979244226452948404D635166546A
SESSION_EXPIRE_TIME : 3600
SESSION_EXPIRE_TIME_EXTENDED : 2592000
TWO_FA_TIMEOUT : 12000
PASSWORD_LESS_CREATE_TIMEOUT : 360
SERVER_NAME: MyProject

PROTOCAL : http
MODE: dev

BACKEND_HOST : localhost
BACKEND_PORT : 8080

STATIC_HOST : localhost
STATIC_PORT : 8081

FRONTEND_HOST : localhost
FRONTEND_PORT : 3001

UPLOAD_DIR_ROOT : ../file_server

BACKEND_CORS_ORIGINS :
  - http://localhost:3001
  - http://localhost
ALLOWED_EMAIL_HOST:
  - gmail.com
PROJECT_NAME : MyProject

POSTGRES_SERVER : ""
POSTGRES_PORT : 5050
POSTGRES_USER : ""
POSTGRES_PASSWORD : ""
POSTGRES_DB : ""

SMTP_TLS : False
SMTP_PORT : 1025
SMTP_HOST : localhost
SMTP_USER : smptuser
SMTP_PASSWORD : smtppass

EMAILS_FROM_EMAIL : "noreply@app.local"
EMAIL_RESET_TOKEN_EXPIRE_HOURS : 48
EMAIL_VERIFY_EXPIRE_HOURS : 48
EMAIL_TEMPLATES_DIR : templates/email-templates/

FIRST_SUPERUSER : "admin@app.local"
FIRST_SUPERUSER_PASSWORD : "password"
USERS_OPEN_REGISTRATION : True

ARGON_MEMORY      : 65536
ARGON_TIME      : 1
ARGON_ITERATIONS  : 3
ARGON_PARALLELISM : 2
ARGON_SALT_LENGTH : 16
ARGON_KEY_LENGTH  : 32
