API_STR: "/api/v1"
SESSION_EXPIRE_TIME: 3600
SESSION_EXPIRE_TIME_EXTENDED: 2592000
TWO_FA_TIMEOUT: 12000
PASSWORD_LESS_CREATE_TIMEOUT: 360
SERVER_NAME: AaryaPay

SECRET_KEY: fzAng9P5nxQCaxh4+sExTCdRI2++KmwBRKohfBJ8RuuD5sb/gfzu1BrFiJeGJudEOwAp1ZVekbVwWrLmRlzu1g==

PROTOCAL: http
MODE: dev

BACKEND_HOST: localhost
BACKEND_PORT: 8080

STATIC_HOST: localhost
STATIC_PORT: 8081

FRONTEND_HOST: localhost
FRONTEND_PORT: 3001

UPLOAD_DIR_ROOT: ../file_server

BACKEND_CORS_ORIGINS:
  - http://localhost:3001
  - http://localhost
ALLOWED_EMAIL_HOST:
  - gmail.com
PROJECT_NAME: AaryaPay

POSTGRES_SERVER: "localhost"
POSTGRES_PORT: 5432
POSTGRES_USER: "postadmin"
POSTGRES_PASSWORD: "postpass"
POSTGRES_DB: "aaryapay"

REDIS_SERVER: localhost
REDIS_PORT: 6379
REDIS_USER: default
REDIS_PASSWORD: redispass

SMTP_TLS: True
SMTP_PORT: 1025
SMTP_HOST: localhost
SMTP_USER: smptuser
SMTP_PASSWORD: smtppass

EMAILS_FROM_EMAIL: "noreply@app.local"
EMAIL_RESET_TOKEN_EXPIRE_HOURS: 48
EMAIL_VERIFY_EXPIRE_HOURS: 48
EMAIL_TEMPLATES_DIR: templates/email-templates/

FIRST_SUPERUSER: "admin@app.local"
FIRST_SUPERUSER_PASSWORD: "password"
USERS_OPEN_REGISTRATION: True

ARGON_MEMORY: 65536
ARGON_TIME: 1
ARGON_ITERATIONS: 3
ARGON_PARALLELISM: 2
ARGON_SALT_LENGTH: 16
ARGON_KEY_LENGTH: 32
