API_STR: "/api/v1"
SESSION_EXPIRE_TIME: 3600
SESSION_EXPIRE_TIME_EXTENDED: 2592000
TWO_FA_TIMEOUT: 12000
PASSWORD_LESS_CREATE_TIMEOUT: 360
SERVER_NAME: AaryaPay

SECRET_KEY: fzAng9P5nxQCaxh4+sExTCdRI2++KmwBRKohfBJ8RuuD5sb/gfzu1BrFiJeGJudEOwAp1ZVekbVwWrLmRlzu1g==

PROTOCAL: http
MODE: prod

BACKEND_HOST: 155.248.247.182
BACKEND_PORT: 41973

STATIC_HOST: arpandaze.tech
STATIC_PORT: 80

FRONTEND_HOST: 155.248.247.182
FRONTEND_PORT: 41973

UPLOAD_DIR_ROOT: ../.files

BACKEND_CORS_ORIGINS:
  - http://155.248.247.182:41973
  - http://arpandaze.tech
ALLOWED_EMAIL_HOST:
  - gmail.com
PROJECT_NAME: AaryaPay

POSTGRES_SERVER: localhost
POSTGRES_PORT: 32221
POSTGRES_USER: "postadmin"
POSTGRES_PASSWORD: 11227f9c054247bdb73af64b6a779c0d
POSTGRES_DB: "aaryapay"

REDIS_SERVER: localhost
REDIS_PORT: 34232
REDIS_USER: default
REDIS_PASSWORD: 6f705d74ff8e4fa69f2746dceab73dfa

SMTP_TLS: False
SMTP_PORT: 1025
SMTP_HOST: localhost
SMTP_USER: smptuser
SMTP_PASSWORD: smtppass

EMAILS_FROM_EMAIL: "noreply@app.local"
EMAIL_RESET_TOKEN_EXPIRE_HOURS: 48
EMAIL_VERIFY_EXPIRE_HOURS: 48
EMAIL_TEMPLATES_DIR: templates/email-templates/

FIRST_SUPERUSER: "admin@app.local"
FIRST_SUPERUSER_PASSWORD: "password"
USERS_OPEN_REGISTRATION: True

ARGON_MEMORY: 65536
ARGON_TIME: 1
ARGON_ITERATIONS: 3
ARGON_PARALLELISM: 2
ARGON_SALT_LENGTH: 16
ARGON_KEY_LENGTH: 32

KEY_VALIDITY_TIME_HOURS: 72
