api:
  dashboard: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
  postgres:
    address: ":5432"
  redis:
    address: ":6379"

providers:
  file:
    directory: "/etc/traefik"
    watch: true

certificatesResolvers:
  tlsresolver:
    acme:
      email: arpankoirala12@gmail.com
      storage: /acme/acme.json
      httpChallenge:
        entryPoint: web
